'use strict';
const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),assert=require('node:assert/strict'),{spawnSync,spawn}=require('node:child_process');
const ROOT=path.join(__dirname,'..'),PY=require('./env.cjs').PY;
const cfg=JSON.parse(fs.readFileSync(path.join(ROOT,'config.json'))),contract=require('../scripts/contracts.cjs');
const {collectHistory,auditHistory,START}=require('../scripts/history_core.cjs');
const base=fs.mkdtempSync(path.join(os.tmpdir(),'bg-extra-'));let count=0;const test=(name,f)=>{f();count++;console.log('PASS',name);};
const identity={userId:'fixture',subaccountId:3,accountKey:'fixture-3'};
function fixture(){const d=fs.mkdtempSync(path.join(base,'case-'));fs.mkdirSync(path.join(d,'state'));put(d,'config.json',cfg);put(d,'state/account_identity.json',identity);fs.cpSync(path.join(ROOT,'scripts'),path.join(d,'scripts'),{recursive:true});return d;}
function put(d,p,v){fs.writeFileSync(path.join(d,p),JSON.stringify(v));}const read=(d,p)=>JSON.parse(fs.readFileSync(path.join(d,p)));
function importFile(d,f){return spawnSync(process.execPath,[path.join(ROOT,'scripts/import_ledger.cjs'),path.join(d,f)],{env:{...process.env,BG_ROOT:d},encoding:'utf8',timeout:10000});}
function store(d,command,v){const r=spawnSync(PY,[path.join(ROOT,'scripts/history_store.py'),command],{env:{...process.env,BG_ROOT:d},input:v?JSON.stringify(v):undefined,encoding:'utf8',timeout:10000});return{...r,value:r.status===0?JSON.parse(r.stdout):null};}
async function main(){
 test('invalid config is refused before trading',()=>{assert.throws(()=>contract.validateConfig({...cfg,stopLossPct:0}));assert.throws(()=>contract.validateConfig({...cfg,riskBudgetPct:NaN}));});
 test('actual collateral owner must match pin',()=>assert.throws(()=>contract.collateralFor({'other-3':{}},identity),/IDENTITY/));
 test('decimal formatting normalization confirms identical parameters',()=>assert(contract.gridConfirmed({symbol:'ETH_USDC_PERP',allocationUsd:'500.00',priceLow:'90.000',priceHigh:'110.00',levels:'20',takeProfitPercentage:'10',stopLossPercentage:'6',direction:'Neutral',enabled:true,closePositionsOnStop:true},{market:'ETH-PERP',value:500,lower:90,upper:110,count:20},cfg)));
 test('valid zero exposure / no liquidation price is accepted',()=>assert.equal(contract.positionsRisk([{symbol:'ETH_USDC_PERP',netQuantity:0,markPrice:null,estLiquidationPrice:null}],cfg,identity).blocked,false));
 test('hex and boolean quantities cannot masquerade as flat',()=>{for(const q of ['0x0',false,[]])assert(contract.positionsRisk([{symbol:'ETH_USDC_PERP',netQuantity:q}],cfg,identity).blocked);});
 test('actual market margin dominates leverage-only estimate',()=>assert.equal(contract.marginEstimate(500,cfg,{type:'sqrt',base:.2,factor:0}),100));
 test('size-dependent IMF grows conservatively',()=>assert.equal(contract.marginEstimate(10000,cfg,{type:'sqrt',base:.02,factor:.003}),3000));
 const d=fixture(),now=START+2*86400000;
 const fill={id:'old-late',timestamp:START+1000,price:'100',quantity:'1',fee:'.1',feeSymbol:'USDC',isMaker:true};
 let h={accountKey:identity.accountKey,symbols:{X:{from:START,lastTo:now,fills:{},auditedThrough:START,incomplete:false}},acquiredAt:new Date(now).toISOString(),asOf:new Date(now).toISOString(),incomplete:false};
 h=await auditHistory(h,['X'],now,async(s,lo,hi)=>fill.timestamp>=lo&&fill.timestamp<=hi?[fill]:[],10);
 test('deep audit captures fills older than overlap horizon',()=>{assert(h.symbols.X.fills['old-late']);assert.equal(h.auditIncomplete,false);});
 let saved=store(d,'save',h);test('SQLite raw ledger and fee summary persisted atomically',()=>{assert.equal(saved.status,0,saved.stderr);assert.equal(saved.value.symbols.X.feeUsd,.1);assert.equal(saved.value.symbols.X.makerN,1);});
 saved=store(d,'save',h);test('replaying SQLite fills does not increment totals again',()=>assert.equal(saved.value.symbols.X.makerN,1));
 const bad=structuredClone(h);bad.symbols.X.fills['old-late'].fee='.2';const rejected=store(d,'save',bad);
 test('immutable SQLite conflict rolls back',()=>assert.notEqual(rejected.status,0));
 put(d,'state/account_identity.json',{userId:'other',subaccountId:3,accountKey:'other-3'});test('SQLite history cannot load under another owner',()=>assert.notEqual(store(d,'load').status,0));
 put(d,'state/account_identity.json',identity);
 const ledger=(from,through,events=[])=>({accountKey:identity.accountKey,subaccountId:3,events,coverage:{cashflow:{from,through,source:'reconciled fixture'}}});
 put(d,'a.json',ledger('2026-09-30T00:00:00Z','2026-10-01T00:00:00Z'));put(d,'b.json',ledger('2026-10-01T00:00:00Z','2026-10-02T00:00:00Z'));
 assert.equal(importFile(d,'a.json').status,0);assert.equal(importFile(d,'b.json').status,0);
 test('incremental coverage retains earliest start and newest end',()=>{const c=read(d,'state/attribution_ledger.json').coverage.cashflow;assert.equal(c.from,'2026-09-30T00:00:00.000Z');assert.equal(c.through,'2026-10-02T00:00:00.000Z');});
 const previous=fs.readFileSync(path.join(d,'state/attribution_ledger.json'),'utf8');put(d,'gap.json',ledger('2026-10-03T00:00:00Z','2026-10-04T00:00:00Z'));assert.notEqual(importFile(d,'gap.json').status,0);
 test('gapped coverage cannot erase a valid old ledger',()=>assert.equal(fs.readFileSync(path.join(d,'state/attribution_ledger.json'),'utf8'),previous));
 for(let i=0;i<6;i++)put(d,`parallel-${i}.json`,ledger('2026-09-30T00:00:00Z','2026-10-02T00:00:00Z',[{id:'deposit-'+i,type:'cashflow',amountUsd:i,at:'2026-10-01T00:00:00Z',source:'reconciled fixture'}]));
 const statuses=await Promise.all(Array.from({length:6},(_,i)=>new Promise((resolve,reject)=>{const p=spawn(process.execPath,[path.join(ROOT,'scripts/import_ledger.cjs'),path.join(d,`parallel-${i}.json`)],{env:{...process.env,BG_ROOT:d},stdio:'ignore'});p.on('error',reject);p.on('close',resolve);})));test('parallel imports lose no events',()=>{assert(statuses.every(c=>c===0));assert.equal(read(d,'state/attribution_ledger.json').events.length,6);});
 const meta={runId:'r',planId:'p',identity,at:new Date().toISOString()};put(d,'state/actions_meta.json',meta);put(d,'state/run_context.json',{runId:'r',identity,ownerPid:process.pid,ownerStart:require('../scripts/execution_lease.cjs').ownerStart(process.pid)});fs.writeFileSync(path.join(d,'state/last_round_status'),'running');
 test('live execution lease is accepted',()=>require('../scripts/execution_lease.cjs').verifyLease(d,meta,identity));
 put(d,'state/run_context.json',{runId:'r',identity,ownerPid:99999999,ownerStart:'dead'});test('dead owner invalidates execution even with old matching plan',()=>assert.throws(()=>require('../scripts/execution_lease.cjs').verifyLease(d,meta,identity),/LEASE/));
 const lease=require('../scripts/execution_lease.cjs');put(d,'state/run_context.json',{runId:'r',identity,ownerPid:process.pid,ownerStart:lease.ownerStart(process.pid)});
 test('unknown and future lease timestamps are rejected',()=>{for(const at of ['bad',new Date(Date.now()+120000).toISOString()])assert.throws(()=>lease.verifyLease(d,{...meta,at},identity),/LEASE/);});
 put(d,'state/actions_meta.json',{...meta,runId:'different'});test('same plan ID under another run cannot retain lease',()=>assert.throws(()=>lease.verifyLease(d,meta,identity),/LEASE/));
 put(d,'state/actions_meta.json',{...meta,configHash:contract.hash(cfg)});put(d,'config.json',{...cfg,minScore:cfg.minScore+1});
 test('configuration changed after planning revokes actor writes',()=>assert.throws(()=>lease.verifyLease(d,{...meta,configHash:contract.hash(cfg)},identity),/CONFIG_CHANGED/));put(d,'config.json',cfg);
 const held=fixture(),grid={market:'OLD-PERP',symbol:'OLD_USDC_PERP',range:['90','110'],allocationRaw:1000,pnlRaw:120,pnlPct:12,status:'Disabled',nativeTP:10,nativeSL:6,nativeCloseOnStop:true};
 const obs={identity,at:new Date().toISOString(),gridRows:[grid],positions:[],ledger:[],margin:{totalEquity:'1000',availableEquity:'500',openPnl:'0'}};put(held,'state/observed.json',obs);put(held,'state/risk.json',{peakEquity:1000,paused:null});put(held,'state/pending_stops.json',{});
 const pause=(m,op)=>spawnSync(process.execPath,[path.join(ROOT,'scripts/manual_pause.cjs'),m,op],{env:{...process.env,BG_ROOT:held},encoding:'utf8',timeout:55000});
 const decide=()=>spawnSync(process.execPath,[path.join(ROOT,'scripts/decide.cjs')],{env:{...process.env,BG_ROOT:held,BG_OFFLINE:'1'},encoding:'utf8'});
 assert.equal(pause('OLD-PERP','hold').status,0);assert.equal(decide().status,0);
 test('explicit hold preserves Disabled grid even past TP',()=>assert(!read(held,'state/actions.json').some(a=>a.act==='stop')));
 put(held,'state/observed.json',{...obs,margin:{...obs.margin,totalEquity:'100'}});assert.equal(decide().status,0);
 test('account breaker overrides explicit local hold',()=>assert(read(held,'state/actions.json').some(a=>a.act==='stop')));
 put(held,'state/observed.json',{...obs,gridRows:[]});test('hold can be cleared after grid has disappeared',()=>assert.equal(pause('OLD-PERP','clear').status,0));
 const corruptPause='[]';fs.writeFileSync(path.join(held,'state/manual_pauses.json'),corruptPause);const refused=pause('*','hold');
 test('malformed pause registry is not silently overwritten',()=>{assert.notEqual(refused.status,0);assert.equal(fs.readFileSync(path.join(held,'state/manual_pauses.json'),'utf8'),corruptPause);});
 put(held,'state/manual_pauses.json',{});put(held,'state/observed.json',obs);
 const holdStatuses=await Promise.all(['OLD-PERP','*'].map(m=>new Promise((resolve,reject)=>{const p=spawn(process.execPath,[path.join(ROOT,'scripts/manual_pause.cjs'),m,'hold'],{env:{...process.env,BG_ROOT:held},stdio:'ignore'});p.on('error',reject);p.on('close',resolve);})));test('concurrent manual intentions retain both edits',()=>{assert(holdStatuses.every(c=>c===0));assert.deepEqual(Object.keys(read(held,'state/manual_pauses.json')).sort(),['*','OLD-PERP']);});
 const {collectSource}=require('../scripts/attribution_sources.cjs');
 let source=await collectSource(identity,async()=>[{subaccountId:'3',userId:'fixture'}],async()=>{});
 test('raw attribution accepts equivalent numeric account fields',()=>{assert(source.complete);assert(source.scopeVerifiedInRows);});
 source=await collectSource(identity,async()=>[{subaccountId:2}],async()=>{});test('foreign source rows fail closed',()=>{assert(!source.complete);assert.equal(source.rows.length,0);});
 source=await collectSource(identity,async()=>[{id:'unscoped'}],async()=>{});test('source without owner fields never claims row scope',()=>{assert(source.complete);assert(!source.scopeVerifiedInRows);});
 const full=Array.from({length:1000},(_,i)=>({id:String(i),subaccountId:3}));source=await collectSource(identity,async()=>full,async()=>{});
 test('repeated full page cannot masquerade as progress',()=>{assert(!source.complete);assert.match(source.error,/no progress/);assert.equal(source.rows.length,1000);});
 source=await collectSource(identity,async()=>full,async()=>{},1000);test('source pagination cap is an explicit failure',()=>{assert(!source.complete);assert.match(source.error,/limit/);});
 let checks=0;source=await collectSource(identity,async()=>[],async()=>{if(++checks===2)throw Error('owner switched');});test('session loss at final confirmation invalidates source completion',()=>assert(!source.complete));
 const raw=fixture();put(raw,'state/history_browser.json',{spaceId:51,page:'p2'});const AsyncFunction=Object.getPrototypeOf(async function(){}).constructor;
 const sourceCode=fs.readFileSync(path.join(ROOT,'scripts/collect_attribution.mjs'),'utf8').replace("const ROOT='__BG_ROOT__';","const ROOT="+JSON.stringify(raw)+";");
 let foreign=false;const page={fetch:async url=>({status:200,body:JSON.stringify(url.includes('/collateral')?{[foreign?'other-3':'fixture-3']:{netEquity:1000}}:[{id:'row',subaccountId:3,userId:'fixture'}])})};
 await new AsyncFunction('taskSpace','console',sourceCode)(async()=>({page:()=>page}),{log(){}});const savedSource=fs.readFileSync(path.join(raw,'state/attribution_sources.json'),'utf8');
 test('production raw source entry persists all sources with bound identity',()=>{const s=JSON.parse(savedSource);assert.equal(s.identity.accountKey,identity.accountKey);assert(Object.values(s.sources).every(r=>r.complete));});
 foreign=true;await assert.rejects(()=>new AsyncFunction('taskSpace','console',sourceCode)(async()=>({page:()=>page}),{log(){}}),/IDENTITY/);
 test('production raw source entry preserves previous evidence on owner loss',()=>assert.equal(fs.readFileSync(path.join(raw,'state/attribution_sources.json'),'utf8'),savedSource));
 const riskBefore=fs.readFileSync(path.join(held,'state/risk.json'),'utf8');
 const unboundWriter=spawnSync(PY,[path.join(ROOT,'scripts/risk_write.py'),JSON.stringify({peakEquity:99999})],{env:{...process.env,BG_ROOT:held},encoding:'utf8'});
 test('risk writer requires pinned account identity even for direct invocation',()=>{assert.notEqual(unboundWriter.status,0);assert.equal(fs.readFileSync(path.join(held,'state/risk.json'),'utf8'),riskBefore);});
 put(held,'state/manual_pauses.json',{});put(held,'state/pending_stops.json',{'GONE-PERP':{at:new Date().toISOString(),reason:'unbound'}});put(held,'state/observed.json',{...obs,gridRows:[]});assert.equal(decide().status,0);
 test('unbound pending entries cannot dispatch account cleanup',()=>{assert(!read(held,'state/actions.json').some(a=>a.market==='GONE-PERP'));});
 const zero=fixture(),zeroId={userId:'fixture',subaccountId:0,accountKey:'fixture'};
 put(zero,'config.json',{...cfg,subaccountId:0,maxGrids:0});put(zero,'state/account_identity.json',zeroId);put(zero,'state/observed.json',{...obs,identity:zeroId,gridRows:[]});put(zero,'state/risk.json',{peakEquity:1000,paused:null});
 const zeroDecision=spawnSync(process.execPath,[path.join(ROOT,'scripts/decide.cjs')],{env:{...process.env,BG_ROOT:zero,BG_OFFLINE:'1'},encoding:'utf8'});
 test('main account zero is preserved in production action metadata',()=>{assert.equal(zeroDecision.status,0,zeroDecision.stderr);assert.equal(read(zero,'state/actions_meta.json').subaccountId,0);});
 const ambiguous=[{symbol:'ETH_USDC_PERP',netQuantity:'0'},{symbol:'ETH_USDC_PERP',netQuantity:'1'}];
 test('duplicate position symbols cannot masquerade as flat exposure',()=>assert(contract.positionsRisk(ambiguous,cfg,identity).blocked));
 let pend={'ETH-PERP':{at:new Date().toISOString(),reason:'test'}};
 const stopped=await require('../scripts/act_core.cjs').makeStopGrid({loadPending:async()=>({pending:pend}),savePending:async p=>{pend=p;},getAutomation:async()=>({params:{symbols:[]}}),jget:async()=>ambiguous})('ETH-PERP',null,'verify',[]);
 test('production stop refuses duplicate zero/live target rows and retains intent',()=>{assert.equal(stopped.done,false);assert(pend['ETH-PERP']);});
 console.log(`${count} extra contract/storage scenarios passed`);
}
main().finally(()=>fs.rmSync(base,{recursive:true,force:true})).catch(e=>{console.error(e);process.exitCode=1;});
