// Real evaluator cancellation/owner-death test. The only 'write' is a temp marker.
const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),{spawn,spawnSync}=require('node:child_process');
const ROOT=path.join(__dirname,'..'),dir=fs.mkdtempSync(path.join(os.tmpdir(),'bg-cancel-probe-'));
fs.mkdirSync(path.join(dir,'state'));const cfg=JSON.parse(fs.readFileSync(path.join(ROOT,'config.json'))),identity={userId:'fixture',subaccountId:3,accountKey:'fixture-3'};
fs.writeFileSync(path.join(dir,'config.json'),JSON.stringify(cfg));fs.writeFileSync(path.join(dir,'state/account_identity.json'),JSON.stringify(identity));
const prepare=`const fs=require('fs');const c=JSON.parse(fs.readFileSync(process.env.BG_ROOT+'/state/run_context.json'));fs.writeFileSync(process.env.BG_ROOT+'/state/actions_meta.json',JSON.stringify({runId:c.runId,identity:c.identity,planId:'cancel',at:new Date().toISOString()}));`;
fs.writeFileSync(path.join(dir,'prepare.cjs'),prepare);
const probe=`const fs=await import('node:fs/promises');const {createRequire}=await import('node:module');const req=createRequire(${JSON.stringify(path.join(ROOT,'scripts/act.mjs'))});const root=${JSON.stringify(dir)};const c=JSON.parse(await fs.readFile(root+'/state/run_context.json','utf8'));const m=JSON.parse(await fs.readFile(root+'/state/actions_meta.json','utf8'));req('./execution_lease.cjs').verifyLease(root,m,c.identity);await fs.writeFile(root+'/started','ready');await new Promise(r=>setTimeout(r,6000));let rejected=false;try{req('./execution_lease.cjs').verifyLease(root,m,c.identity);}catch{rejected=true;}if(!rejected)await fs.writeFile(root+'/would-write','unsafe');await fs.writeFile(root+'/done',JSON.stringify({rejected}));`;
fs.writeFileSync(path.join(dir,'probe.mjs'),probe);fs.writeFileSync(path.join(dir,'runner.sh'),`#!/bin/bash\nexport BG_ROOT=${JSON.stringify(dir)}\n${process.execPath} ${JSON.stringify(path.join(ROOT,'scripts/run_events.cjs'))} start\n${process.execPath} ${JSON.stringify(path.join(dir,'prepare.cjs'))}\nego-browser nodejs < ${JSON.stringify(path.join(dir,'probe.mjs'))}\n`);
const child=spawn('/Users/nick/.browser-use-env/bin/python3',[path.join(ROOT,'scripts/with_lock.py'),'/bin/bash',path.join(dir,'runner.sh')],{env:{...process.env,BG_ROOT:dir},stdio:'ignore'});
const wait=ms=>new Promise(r=>setTimeout(r,ms));
(async()=>{let started=false;for(let i=0;i<200;i++){if(fs.existsSync(path.join(dir,'started'))){started=true;break;}await wait(25);}if(!started)throw Error('evaluator did not start');const c=JSON.parse(fs.readFileSync(path.join(dir,'state/run_context.json')));process.kill(c.ownerPid,'SIGKILL');for(let i=0;i<320;i++){if(fs.existsSync(path.join(dir,'done')))break;await wait(25);}if(fs.existsSync(path.join(dir,'would-write')))throw Error('dead owner retained an executable lease');const status=fs.readFileSync(path.join(dir,'state/last_round_status'),'utf8');if(status!=='aborted')throw Error('abnormal exit not recorded');console.log({realEgoEvaluator:true,ownerKilled:true,staleWritePrevented:true,evaluatorResult:fs.existsSync(path.join(dir,'done'))?JSON.parse(fs.readFileSync(path.join(dir,'done'))):'cancelled before continuation',supervisorStatus:status});})().catch(e=>{console.error(e);process.exitCode=1;}).finally(()=>{try{child.kill('SIGTERM');}catch{}fs.rmSync(dir,{recursive:true,force:true});});
