// Prepare an entirely disposable, mocked account for ego's real nodejs evaluator.
const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),{spawnSync}=require('node:child_process');
const ROOT=path.join(__dirname,'..'),dir=fs.mkdtempSync(path.join(os.tmpdir(),'bg-ego-probe-'));
const cfg=JSON.parse(fs.readFileSync(path.join(ROOT,'config.json'))),identity={userId:'fixture',subaccountId:3,accountKey:'fixture-3'};
fs.mkdirSync(path.join(dir,'state'));fs.cpSync(path.join(ROOT,'scripts'),path.join(dir,'scripts'),{recursive:true});
fs.writeFileSync(path.join(dir,'config.json'),JSON.stringify(cfg));fs.writeFileSync(path.join(dir,'state/account_identity.json'),JSON.stringify(identity));fs.writeFileSync(path.join(dir,'state/risk.json'),JSON.stringify({peakEquity:1000,paused:null,accountKey:identity.accountKey}));
const driver=`const fs=await import('node:fs/promises');const path=await import('node:path');const {createRequire}=await import('node:module');const req=createRequire(${JSON.stringify(path.join(ROOT,'scripts/act.mjs'))});const {verifyLease}=req('./execution_lease.cjs');const root=${JSON.stringify(dir)};const ctx=JSON.parse(await fs.readFile(root+'/state/run_context.json','utf8'));const cfg=JSON.parse(await fs.readFile(root+'/config.json','utf8'));const identity=ctx.identity;const {hash}=req('./contracts.cjs');const actions=[{act:'create',market:'ETH-PERP',lower:90,upper:110,count:20,value:500}];const meta={runId:ctx.runId,planId:'ego-probe',identity,at:new Date().toISOString(),configHash:hash(cfg),actionsHash:hash(actions),subaccountId:3,riskWriteOk:true};await fs.writeFile(root+'/state/actions.json',JSON.stringify(actions));await fs.writeFile(root+'/state/actions_meta.json',JSON.stringify(meta));let autos=[],writes=0;const page={goto:async()=>{},waitForTimeout:async()=>{},fetch:async(url,opt={})=>{const u=new URL(url);let data;if(opt.method==='POST')return{status:200,body:'{}'};if(opt.method==='PATCH'){writes++;const e=JSON.parse(opt.body).params.symbols[0];autos=autos.filter(g=>g.symbol!==e.symbol);if(e.operation!=='Delete')autos.push(e);return{status:200,body:'{}'};}if(u.pathname.endsWith('/automation'))data={params:{symbols:autos}};else if(u.pathname.endsWith('/position'))data=[];else if(u.pathname.endsWith('/collateral'))data={'fixture-3':{netEquity:'1000',netEquityAvailable:'500'}};else if(u.pathname.endsWith('/account'))data={leverageLimit:'10',liquidating:false};else if(u.pathname.endsWith('/markets'))data=[{symbol:'ETH_USDC_PERP',imfFunction:{type:'sqrt',base:'.02',factor:'.00001'}}];else if(u.pathname.endsWith('/markPrices'))data=[{symbol:'ETH_USDC_PERP',markPrice:'100'}];else if(u.pathname.endsWith('/orders'))data=Array.from({length:20},()=>({symbol:'ETH_USDC_PERP'}));else throw Error('unexpected mock URL');return{status:200,body:JSON.stringify(data)};}};const source=(await fs.readFile(${JSON.stringify(path.join(ROOT,'scripts/act.mjs'))},'utf8')).replace('const ROOT = "__BG_ROOT__";','const ROOT = '+JSON.stringify(root)+';');const AsyncFunction=Object.getPrototypeOf(async function(){}).constructor;await new AsyncFunction('taskSpace','process',source)(async()=>({page:()=>page}),{exit:c=>{throw Error('mock exit '+c)}});const result=JSON.parse(await fs.readFile(root+'/state/act_results.json','utf8'));if(result.results.filter(r=>r.act==='create'&&r.done).length!==1)throw Error('real runner lifecycle failed');console.log({realEgoEvaluator:true,mockedWrites:writes,pending:JSON.parse(await fs.readFile(root+'/state/pending_stops.json','utf8')),status:result.status,root});`;
fs.writeFileSync(path.join(dir,'probe.mjs'),driver);
fs.writeFileSync(path.join(dir,'runner.sh'),`#!/bin/bash\nexport BG_ROOT=${JSON.stringify(dir)}\n${JSON.stringify(process.execPath)} ${JSON.stringify(path.join(ROOT,'scripts/run_events.cjs'))} start\nego-browser nodejs < ${JSON.stringify(path.join(dir,'probe.mjs'))}\n`);
const r=spawnSync(require('./env.cjs').PY,[path.join(ROOT,'scripts/with_lock.py'),'/bin/bash',path.join(dir,'runner.sh')],{env:{...process.env,BG_ROOT:dir},encoding:'utf8',timeout:30000});
process.stdout.write(r.stdout);process.stderr.write(r.stderr);fs.rmSync(dir,{recursive:true,force:true});process.exit(r.status??1);
