'use strict';
const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),assert=require('node:assert/strict'),zlib=require('node:zlib'),{spawnSync}=require('node:child_process');
const {chooseBaseline,chooseCheckpoint,validateWindow,collectPeriod,reconcile}=require('../scripts/verified_window.cjs');
const {hash}=require('../scripts/contracts.cjs');
const root=path.join(__dirname,'..'),base=fs.mkdtempSync(path.join(os.tmpdir(),'bg-window-')),identity={userId:'fixture',subaccountId:3,accountKey:'fixture-3'};
const now=Date.now(),start=new Date(now-3600000).toISOString(),end=new Date(now-600000).toISOString(),paymentAt=new Date(now-1800000).toISOString();let count=0;
const check=(name,fn)=>{fn();count++;console.log('PASS',name);};
const rows=[{at:new Date(now-7200000).toISOString(),equity:400},{accountKey:identity.accountKey,at:start,equity:500,dryrun:true},{accountKey:identity.accountKey,at:end,equity:600}];
const window=chooseBaseline(rows,identity,now);
const src=(rows=[],extra={})=>({from:start,through:end,complete:true,rows,...extra});
const capture=()=>({identity,equityAt:end,asOf:end,equity:600,captureHash:'fixture',sources:{funding:src([{userId:'fixture',subaccountId:3,symbol:'ETH_USDC_PERP',quantity:'-1',intervalEndTimestamp:paymentAt}]),interest:src([{positionId:'lend',paymentType:'Lend',symbol:'USDC',quantity:'.2',timestamp:paymentAt}],{routingVerified:true}),deposits:src([],{routingVerified:true}),withdrawals:src(),platformCredits:src([],{scope:'user-wide-inclusive'})}});
function put(dir,file,data){fs.mkdirSync(path.dirname(path.join(dir,file)),{recursive:true});fs.writeFileSync(path.join(dir,file),JSON.stringify(data));}
async function main(){
 check('baseline uses earliest identity-bound real readonly observation',()=>{assert.equal(window.baseline.at,start);assert.equal(window.baseline.equity,500);});
 check('legacy and simulated observations cannot establish verified baseline',()=>assert.throws(()=>chooseBaseline([rows[0],{...rows[1],simulated:true}],identity,now)));
 check('wrong owner baseline is refused',()=>assert.throws(()=>validateWindow(window,{userId:'other',subaccountId:3,accountKey:'other-3'})));
 check('baseline amount is bound to its original measured source',()=>assert.throws(()=>validateWindow({...window,baseline:{...window.baseline,equity:999}},identity),/binding/));
 check('mature checkpoint excludes latest possibly unindexed minute',()=>assert.equal(chooseCheckpoint([...rows,{...rows[2],at:new Date(now-1000).toISOString()}],window,now).at,end));
 check('stale accounting checkpoint is refused',()=>assert.throws(()=>chooseCheckpoint(rows,window,now+7200000)));
 let out=reconcile(window,capture());
 check('complete zero-capital scan computes net return without subtracting fees twice',()=>{assert.equal(out.report.netPnl,100);assert.equal(out.report.funding,-1);assert.equal(out.report.interest,.2);assert.equal(out.report.reward,0);assert.equal(out.report.otherTradingAndValuationPnl,100.8);assert(out.report.decompositionComplete);});
 const badBoundary=capture();badBoundary.equityAt=new Date(now).toISOString();check('equity and cashflow cutoff must match exactly',()=>assert.throws(()=>reconcile(window,badBoundary),/boundary mismatch/));
 const unscoped=capture();unscoped.sources.platformCredits.rows=[{id:1,status:'confirmed',createdAt:paymentAt,quantity:10,symbol:'USDC'}];out=reconcile(window,unscoped);
 check('unscoped platform receipt cannot be retagged to strategy or treated as zero',()=>{assert.equal(out.report.netPnl,null);assert.equal(out.report.reward,null);});
 const missing=capture();missing.sources.withdrawals.complete=false;check('one incomplete cashflow endpoint blocks net profit',()=>assert.equal(reconcile(window,missing).report.netPnl,null));
 const wrong=capture();wrong.sources.funding.rows[0].subaccountId=2;check('foreign funding leaves decomposition unknown',()=>{const r=reconcile(window,wrong).report;assert.equal(r.funding,null);assert(!r.decompositionComplete);});
 const coin=capture();coin.sources.interest.rows[0].symbol='MON';check('non-USDC payments require valuation instead of assumed parity',()=>assert.equal(reconcile(window,coin).report.interest,null));
 const borrow=capture();borrow.sources.interest.rows[0].paymentType='Borrow';check('borrow interest is a debit',()=>assert.equal(reconcile(window,borrow).report.interest,-.2));
 const duplicate=capture();duplicate.sources.funding.rows.push({...duplicate.sources.funding.rows[0],quantity:'-2'});check('conflicting natural payment identity is not double counted',()=>assert.equal(reconcile(window,duplicate).report.funding,null));
 const previous=reconcile(window,capture()).ledger,failed=capture();failed.sources.funding.complete=false;out=reconcile(window,failed,null,previous);
 check('temporary source outage preserves prior confirmed payments without extending coverage',()=>{assert(out.ledger.events.some(e=>e.type==='funding'));assert.equal(out.report.funding,null);});
 const absent=capture();absent.sources.funding.rows=[];check('confirmed payment disappearing forces reconciliation failure',()=>assert.throws(()=>reconcile(window,absent,null,previous),/disappeared/));
 const manual={accountKey:identity.accountKey,subaccountId:3,events:[{id:'deposit',type:'cashflow',amountUsd:10,at:paymentAt,source:'scoped reviewed export'}],coverage:{cashflow:{from:start,through:end,source:'reviewed export'},reward:{from:start,through:end,source:'reviewed zero rewards'}}};
 check('explicit reviewed capital flow adjusts independent-window return',()=>{const r=reconcile(window,unscoped,manual).report;assert.equal(r.netPnl,90);assert(r.decompositionComplete);});
 check('foreign manual ledger cannot override ambiguity',()=>assert.throws(()=>reconcile(window,unscoped,{...manual,accountKey:'other-3'})));
 const page=await collectPeriod(Date.parse(start),Date.parse(end),async()=>[{timestamp:end},{timestamp:start}],r=>r.timestamp);
 check('descending scan includes end and excludes baseline timestamp',()=>{assert(page.complete);assert.equal(page.rows.length,1);});
 const unordered=await collectPeriod(Date.parse(start),Date.parse(end),async()=>[{timestamp:start},{timestamp:end}],r=>r.timestamp);check('ordering assumptions must be proven before cutoff',()=>assert(!unordered.complete));
 const capped=await collectPeriod(Date.parse(start),Date.parse(end),async()=>Array.from({length:1000},()=>({timestamp:end})),r=>r.timestamp,1);check('full page cap does not declare coverage',()=>assert(!capped.complete));
 const dir=fs.mkdtempSync(path.join(base,'case-'));fs.cpSync(path.join(root,'scripts'),path.join(dir,'scripts'),{recursive:true});const cfg=JSON.parse(fs.readFileSync(path.join(root,'config.json')));put(dir,'config.json',cfg);put(dir,'state/account_identity.json',identity);fs.writeFileSync(path.join(dir,'state/equity_curve.jsonl'),rows.map(JSON.stringify).join('\n')+'\n');
 const oldConfig=fs.readFileSync(path.join(dir,'config.json'),'utf8'),oldCurve=fs.readFileSync(path.join(dir,'state/equity_curve.jsonl'),'utf8');
 const init=()=>spawnSync(process.execPath,[path.join(root,'scripts/init_verified_window.cjs')],{env:{...process.env,BG_ROOT:dir},encoding:'utf8'});
 assert.equal(init().status,0);const before=fs.readFileSync(path.join(dir,'state/verified_window.json'),'utf8');assert.equal(init().status,0);
 check('production init is idempotent and preserves original baseline/config/history',()=>{assert.equal(fs.readFileSync(path.join(dir,'state/verified_window.json'),'utf8'),before);assert.equal(fs.readFileSync(path.join(dir,'config.json'),'utf8'),oldConfig);assert.equal(fs.readFileSync(path.join(dir,'state/equity_curve.jsonl'),'utf8'),oldCurve);});
 // Full production collector entry with mock session I/O; every request must be GET.
 put(dir,'state/accounting_browser.json',{spaceId:cfg.watch.spaceId,page:'p4'});let requests=0;
 const mocked={goto:async()=>{},fetch:async(url,options={})=>{assert.equal(options.method??'GET','GET');requests++;const u=new URL(url);let data=[];
  if(u.pathname.endsWith('/collateral'))data={'fixture-3':{netEquity:'1000'}};
  else if(u.pathname.endsWith('/funding'))data=capture().sources.funding.rows;
  else if(u.pathname.endsWith('/interest'))data=u.searchParams.has('subaccountId')?capture().sources.interest.rows:[{...capture().sources.interest.rows[0],positionId:'main'}];
  else if(u.pathname.endsWith('/deposits')&&!u.searchParams.has('subaccountId'))data=[{id:99,createdAt:start,status:'confirmed'}];
  return {status:200,body:JSON.stringify(data)};
 }};
 const text=fs.readFileSync(path.join(root,'scripts/collect_verified_window.mjs'),'utf8').replace("const ROOT='/Users/nick/CascadeProjects/backpack_grid'","const ROOT="+JSON.stringify(dir));
 const AsyncFunction=Object.getPrototypeOf(async function(){}).constructor;
 await new AsyncFunction('taskSpace','console',text)(async()=>({spaceId:cfg.watch.spaceId,page:()=>mocked}),{log(){}});
 const saved=JSON.parse(fs.readFileSync(path.join(dir,'state/window_accounting.json')));
 check('complete production collector commits coherent report/ledger with only reads',()=>{assert(requests>0);assert.equal(saved.report.netPnl,100);assert(saved.report.decompositionComplete);});
 put(dir,'state/observed.json',{identity,at:new Date().toISOString(),gridRows:[],positions:[],margin:{totalEquity:'600',availableEquity:'500'}});
 const dashboard=()=>spawnSync(process.execPath,[path.join(root,'scripts/dashboard_data.cjs')],{env:{...process.env,BG_ROOT:dir},encoding:'utf8'});
 assert.equal(dashboard().status,0);let published=JSON.parse(fs.readFileSync(path.join(dir,'state/dashboard.json')));
 check('public report replays proof and preserves original historical baseline',()=>{assert.equal(published.verifiedWindow.netPnl,100);assert.equal(published.strategyBaseline,cfg.strategyBaselineUsd);assert(!JSON.stringify(published).includes('accountKey'));});
 put(dir,'state/window_accounting.json',{...saved,report:{...saved.report,netPnl:999}});assert.equal(dashboard().status,0);published=JSON.parse(fs.readFileSync(path.join(dir,'state/dashboard.json')));
 check('report-controlled profit is rejected despite fresh timestamps',()=>assert.equal(published.verifiedWindow.netPnl,null));put(dir,'state/window_accounting.json',saved);
 put(dir,'state/window_status.json',{at:new Date().toISOString(),ok:false});assert.equal(dashboard().status,0);published=JSON.parse(fs.readFileSync(path.join(dir,'state/dashboard.json')));
 check('collector failure withdraws fresh-profit confirmation',()=>{assert.equal(published.verifiedWindow.netPnl,null);assert.equal(published.verifiedWindow.cashflowComplete,false);});
 put(dir,'state/verified_window.json',{...window,baseline:{...window.baseline,equity:400}});const validSaved=fs.readFileSync(path.join(dir,'state/window_accounting.json'),'utf8');
 await assert.rejects(()=>new AsyncFunction('taskSpace','console',text)(async()=>({spaceId:cfg.watch.spaceId,page:()=>mocked}),{log(){}}),/baseline.*(changed|binding)/);
 check('existing accounting window cannot silently be rebased',()=>assert.equal(fs.readFileSync(path.join(dir,'state/window_accounting.json'),'utf8'),validSaved));
 const {archiveResearch}=require('../scripts/research_archive.cjs'),input={cfg,markets:[{symbol:'ETH_USDC_PERP'}],tickers:[],samples:{ETH:{klines:[{close:100}],funding:[]}},output:{generatedAt:end,configHash:'fixed',excluded:[]}};
 archiveResearch(dir,input);archiveResearch(dir,input);const index=fs.readFileSync(path.join(dir,'state/research_archive/index.jsonl'),'utf8').trim().split('\n');const item=JSON.parse(index[0]);
 check('research inputs are preserved immutably and indexed once',()=>{assert.equal(index.length,1);const archived=JSON.parse(zlib.gunzipSync(fs.readFileSync(path.join(dir,item.file))));assert.deepEqual(archived.samples,input.samples);});
 console.log(`${count} verified accounting/research scenarios passed`);
}
main().finally(()=>fs.rmSync(base,{recursive:true,force:true})).catch(e=>{console.error(e);process.exitCode=1;});
