name = "backpack-grid-dashboard"
main = "worker.js"
compatibility_date = "2026-09-01"

rules = [
  { type = "Text", globs = ["**/*.html"] },
]

[[kv_namespaces]]
binding = "DASH"
id = "40e078ae20c84612bce7ddfb711f7992"
